#! /bin/sh
# This shell script is generated by the 'configure' script.  It is invoked in a
# subdirectory of the build tree.  It generates a sed-script in the parent
# directory that is used to adjust includes for header files that reside in a
# subdirectory of /usr/include, etc.
PRG=""
while test $# != 3
do
PRG="$PRG $1"; shift
done
DST=$1
REF=$2
SRC=$3
echo installing $SRC in $DST
case $DST in
/*/include/*)
	TMP=${TMPDIR-/tmp}/`basename $SRC`
	if test ! -f ../headers.sed ; then
		END=`basename $DST`
		for i in `cat $REF/../*/headers |fgrep -v "#"`
		do
			NAME=`basename $i`
			echo "s/<$NAME>/<$END\/$NAME>/" >> ../headers.sed
		done
	fi
	rm -f $TMP
	sed -f ../headers.sed $SRC > $TMP
	eval $PRG $TMP $DST
	rm -f $TMP
	;;
*)
	eval $PRG $SRC $DST
	;;
esac
