/* generated by MKexpanded.sh */
#include <curses.priv.h>
#include <term.h>
#ifdef NCURSES_EXPANDED
void _nc_toggle_attr_on(attr_t *S, attr_t at)
{
 if (PAIR_NUMBER(at) > 0) (*S) = ((*S) & ALL_BUT_COLOR) | (at); else (*S) |= (at); ;
}
void _nc_toggle_attr_off(attr_t *S, attr_t at)
{
 if (FALSE == TRUE) { if (PAIR_NUMBER(at) == 0xff) (*S) &= ~(at); else (*S) &= ~((at)&ALL_BUT_COLOR); } else { if (PAIR_NUMBER(at) > 0x00) (*S) &= ~(at|((((1UL) << 8) - 1UL) << ((0) + 8))); else (*S) &= ~(at); } ;;
}
int _nc_can_clear_with(chtype ch)
{
 return ((ch & ~((((1UL) << ((13) + 8))|((1UL) << ((12) + 8))|((1UL) << ((11) + 8)))|(back_color_erase ? ((((1UL) << 8) - 1UL) << ((0) + 8)):0))) == (' '|0L));
}
int _nc_DelCharCost(int count)
{
 return ((parm_dch != 0) ? SP->_dch_cost : ((delete_character != 0) ? (SP->_dch1_cost * count) : 1000000));
}
int _nc_InsCharCost(int count)
{
 return ((parm_ich != 0) ? SP->_ich_cost : ((insert_character != 0) ? (SP->_ich1_cost * count) : 1000000));
}
void _nc_UpdateAttrs(chtype c)
{
 if (SP->_current_attr != ((c) & (chtype)((~(1UL - 1UL)) << ((0) + 8)))) vidattr(((c) & (chtype)((~(1UL - 1UL)) << ((0) + 8))));;
}
#else /* ! NCURSES_EXPANDED */
void _nc_expanded(void) { }
#endif /* NCURSES_EXPANDED */
