#! /bin/sh
# this script is generated by the configure-script
prefix="/usr/local"
datadir="${prefix}/share"
MKDIRS="/app/ncurses-4.2/mkinstalldirs"
INSTALL="/usr/bin/install -c"
INSTALL_DATA="${INSTALL} -m 644"
TMP=${TMPDIR-/tmp}/man$$
trap "rm -f $TMP" 0 1 2 5 15

verb=$1
shift

mandir=$1
shift

for i in $*
do
case $i in
*.[0-9]*)
	section=`expr "$i" : '.*\.\([0-9]\)[xm]*'`;
	if test $verb = installing ; then
	if test ! -d $mandir/man${section} ; then
		$MKDIRS $mandir/man$section
	fi
	fi
	source=`basename $i`
	target=`grep "^$source" /app/ncurses-4.2/man/man_db.renames | mawk '{print $2}'`
	if test -z "$target" ; then
		echo '? missing rename for '$source
		target="$source"
	fi
	target="$mandir/man$section/$target"
	test $verb = installing && sed -e "s,@DATADIR@,$datadir," < $i | sed -f edit_man.sed >$TMP
	if test $verb = installing ; then
	if ( gzip -f $TMP )
	then
		mv $TMP.gz $TMP
	fi
	fi
	target="$target.gz"
	echo $verb $target
	if test $verb = installing ; then
		$INSTALL_DATA $TMP $target
	else
		rm -f $target
	fi
	;;
esac
done 
